### ISSUE TITLE
Add ML algorithm

### ISSUE THREAD

**Issue by Dhruvinhp** [Dhruvinhp/AI-ML-Algorithms#9]

**Comment by aishwarya-g-thoughtworks** [comment]
I can work on this @Dhruvinhp 
Could you please assign me to this issue.

**Comment by aishwarya-g-thoughtworks** [comment]
I have added Logistic Regression with Iris dataset and raised a PR: https://github.com/Dhruvinhp/AI-ML-Algorithms/pull/12
